<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Billing\AutoMapper\**" />
    <Compile Remove="Billing\Erros\**" />
    <Compile Remove="Billing\Queries\**" />
    <EmbeddedResource Remove="Billing\AutoMapper\**" />
    <EmbeddedResource Remove="Billing\Erros\**" />
    <EmbeddedResource Remove="Billing\Queries\**" />
    <None Remove="Billing\AutoMapper\**" />
    <None Remove="Billing\Erros\**" />
    <None Remove="Billing\Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Poliedro.Billing.Domain\Poliedro.Billing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BillingCreditNote\Services\Factories\TNS\" />
    <Folder Include="BillingCreditNote\Services\Factories\Siigo\" />
    <Folder Include="BillingCreditNote\Services\Selectors\TNS\" />
    <Folder Include="BillingCreditNote\Services\Selectors\Siigo\" />
    <Folder Include="BillingCreditNote\Services\Selectors\Plemsi\" />
    <Folder Include="Billing\Services\Selectors\TNS\" />
    <Folder Include="Billing\Services\Selectors\Siigo\" />
    <Folder Include="CreditNote\Commands\CreateCreditNote\Command\" />
  </ItemGroup>

</Project>
